name: 打包vue项目

on: push

jobs:
  npm-build:
    name: 构建打包
    runs-on: ubuntu-latest
    steps:
    - name: clone代码
      uses: actions/checkout@v4
    - name: 安装依赖
      run: npm install
    - name: 打包
      run: npm run build
    - name: 部署
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist