name: 部署到github pages

on:
  push:
    branches: main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 安装依赖
        run: npm install
      - name: 代码检查
        run: npm run lint
      - name: 单元测试
        run: npm run test:unit
      - name: 打包
        run: npm run build
      - name: 发布
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PROJECT_ACCESS_TOKEN }}
          folder: dist
